### ISSUE TITLE
Selfbuilt release has dependency to wasi_snapshot_preview1 and cannot be loaded in browser

### ISSUE THREAD

**Issue by fabmax** [ashconnell/physx-js#12]
Hi,

I managed to run the build procedure and got my own physx.release.js and .wasm files. However when I try to load them in a browser I get the error "WebAssembly.instantiate(): Import #43 module="wasi_snapshot_preview1" error: module is not an object or function"

I did some googling and apparently WASI is a module which provides system functions within a Node environment and is not available in browsers.

The publicly available physx-js release does not have that issue so I'm guessing it's some kind of config issue and/or I'm doing something wrong?

**Comment by fabmax** [comment]
Ok, I think I solved it

Biggest problem was my own stupidity - I mixed up the files from the public release and my own build.

However another issue was the version of the emscripten docker image. By default docker pulls the latest version which now uses the upstream flavor of emscripten. I'm quite new to emscripten but apparently upstream loads the wasm module as a promise, which means the loader code has to be adjusted.

Essentially it now has to look something like this:

```
PhysX().then(function(PhysX) {
    // initializeStuff...
});
```

**Comment by ashconnell** [comment]
Hi @fabmax glad you got it working!

I should have clamped the version of that docker image to prevent against breaking changes like that. 

I wonder what other goodies emscripten have given us haha

**Comment by fabmax** [comment]
Alright got my setup working pretty nicely now, so I'm going to close this.

Btw. here's a little demo I made with this:
https://fabmax.github.io/kool/kool-js/?demo=phys-joints

It makes pretty heavy use of revolute joints and convex meshes therefore I had to add a few bindings. My binding code is pretty ugly right now, so hopefully I get that a bit better and can put it into a PR.
