### ISSUE TITLE
physx-js as ES6 module

### ISSUE THREAD

**Issue by ivan-enzhaev** [ashconnell/physx-js#15]
Hello,

I am trying to use `physx-js` v0.7.0 as ES6 module but I have this error:

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/wasm". Strict MIME type checking is enforced for module scripts per HTML spec.

Sandbox: https://plnkr.co/edit/B0kWbwZqFipXnFIX?preview

```html
<body>
    <script async src="https://unpkg.com/es-module-shims@1.3.6/dist/es-module-shims.js"></script>

    <script type="importmap">
        {
            "imports": {
                "physx-js": "https://cdn.jsdelivr.net/npm/physx-js@0.7.0/dist/physx.release.js",
                "physx-js-wasm": "https://cdn.jsdelivr.net/npm/physx-js@0.7.0/dist/physx.release.wasm"
            }
        }
    </script>

    <script type="module">
        import physx from "physx-js";
        import physxModule from "physx-js-wasm";

        const PhysX = physx({
            locateFile(path)
            {
                if (path.endsWith(".wasm"))
                {
                    return physxModule;
                }
                return path;
            },
            onRuntimeInitialized()
            {
                console.log("PhysX loaded");
            }
        });
    </script>
</body>
```

**Comment by Sean-Bradley** [comment]
Here is an example of using it in a module, but not "as a module".


[![image](https://github.com/ashconnell/physx-js/assets/6302260/bc9ea4d3-9590-4658-a9a7-ce9f28d9f3c1)](https://sbedit.net/a318767d267c7200e332e740048f00a1c45c679e)

https://sbedit.net/a318767d267c7200e332e740048f00a1c45c679e

**Comment by ivan-enzhaev** [comment]
It is very cool! Thanks a lot! I moved your example to Plunker: https://plnkr.co/edit/c8Pvr7oBlq1B4kAj?preview

I like this Playground very much because it can keep code in the separated files:

![image](https://github.com/ashconnell/physx-js/assets/3908473/6cbe5639-ab65-404c-958e-571ec1c2b0d0)

It works on mobiles very well.

I think it is important to add this code to the index.html:

```html
    <!-- Since import maps are not yet supported by all browsers, its is
        necessary to add the polyfill es-module-shims.js -->
    <script async src="https://unpkg.com/es-module-shims@1.7.3/dist/es-module-shims.js"></script>
```

**Comment by Sean-Bradley** [comment]
I also created a 'physx-js-webidl' example in case you want to try out an alternative. It is also used within a module.

[![image](https://github.com/ashconnell/physx-js/assets/6302260/f33c7f88-5cee-49c7-bf83-417268aa6eb5)](https://sbedit.net/41255c40b512c84951efdd0e83409ea28db2f052)

https://sbedit.net/41255c40b512c84951efdd0e83409ea28db2f052

**Comment by ivan-enzhaev** [comment]
It is awesome! It is very important to be able to draw colliders. I will rewrite your example later to draw colliders with Three.js and pure WebGL.

I already have made an example that draws colliders with Three.js and pure WebGL for Box2D-WASM:
- [Basic Examples of Using Box2D-WASM with Three.js in JavaScript](https://github.com/Birch-san/box2d-wasm/discussions/70)
- [Basic Examples of Using Box2D-WASM with pure WebGL 1.0 in JavaScript](https://github.com/Birch-san/box2d-wasm/discussions/63)

Drawing colliders in Three.js for Box2D-WASM:
- [Plunker Playground](https://plnkr.co/edit/f94oZ5NMSNEZLhMm?preview)
- [GitHub repo with Rollup guide](https://github.com/8Observer8/debug-drawer-box2dwasm-threejs-js)

![debug-drawer-box2dwasm-threejs](https://github.com/ashconnell/physx-js/assets/3908473/e28d4ab4-be08-49b0-b4bb-16ef5c8fbbb9)
