### ISSUE TITLE
Collision detection does not work with versions > 0.0.6

### ISSUE THREAD

**Issue by sebcrozet** [ashconnell/physx-js#6]
Hi!

I am a very beginner with JS and webpack so I may just be doing something wrong. I tried the following steps:
- Cloned this repo.
- `cd example`
- `npm install`
- `npm run start`.

And I get the expect results with falling cubes hitting the ground.

However, if I modify the `package.json` and set the `physx-rs` dependency to its latest version 0.0.9, re-run `npm install` and `npm run start`, I see the falling cubes but they just pass through the ground instead of hitting it. Is there some additional PhysX scene configuration do to in order to make the version 0.0.9 of `physx-rs` work?

**Comment by lirongf** [comment]
I have a different problem than you，I copied it and downloaded it. OK physix.release.js as well as physx.release.wasm , do the same as the browser three example, but the box goes through the plane. How can I correct this mistake?

**Comment by LeXXik** [comment]
I believe the recent version includes filtering now. That requires you to set a group and a mask for your shape.
You can read the how to set up filtering in the manual here:
https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/RigidBodyCollision.html

I also made an example with Playcanvas. You can check how I set filters here:
https://playcanvas.com/project/737359/overview/playcanvas-with-nvidia-physx

```js
    const setupFiltering = function(shape, group, mask) {
        const filterData = new PhysX.PxFilterData(group, mask, 0, 0);
        shape.setSimulationFilterData(filterData);
    };
```
